logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp/webapp.log
  processors:
    parse_json:
      type: parse_json
      field: message
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%f%z"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [parse_json, move_severity]


