name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: csye6225


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PostgreSQL and dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y postgresql
            sudo service postgresql start
            sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${{ env.POSTGRES_PASSWORD }}';"
            sudo -u postgres createdb csye6225    

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: |
            pip install -r requirements.txt
            sudo service postgresql stop 

      - name: Run integration tests
        run: pytest csye6225project/csye6225/tests/test_integration.py
