name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: csye6225
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run integration tests
        run: pytest csye6225project/csye6225/tests/test_integration.py
