name: Packer CI - PR Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: Packer Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build artifact
        run: pip install starlette-deployment
            starlette-deployment build webapp/csyeproject6225/csye6225/main.py:app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-package
          path: build/production-package.tar.gz

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y

      - name: Authenticate with gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Packer Google Compute Engine Plugin
        run: packer plugins install github.com/hashicorp/googlecompute

      - name: Check Packer Template Format
        run: |
          cd packer
          packer fmt -check packer.pkr.hcl
          if [ $? -eq 1 ]; then
            echo "Packer template format is incorrect. Please run 'packer fmt' to format it properly."
            exit 1
          fi

      - name: Validate Packer Template
        run: |
          cd packer
          packer validate packer.pkr.hcl
          if [ $? -ne 0 ]; then
            echo "Packer template validation failed. Please check the template for errors."
            exit 1
          fi
