name: Packer CI - PR Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: Packer Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Project Artifact
        run: |
          tar -czf dist/webapp-1.0.0.tar.gz webapp
        working-directory: ${{ github.workspace }}

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Authenticate with gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Packer Google Compute Engine Plugin
        run: |
          packer plugins install github.com/hashicorp/googlecompute

      - name: Check Packer Template Format
        run: |
          cd packer
          packer fmt -check packer.pkr.hcl
          if [ $? -eq 1 ]; then
            echo "Packer template format is incorrect. Please run 'packer fmt' to format it properly."
            exit 1
          fi

      - name: Validate Packer Template
        run: |
          cd packer
          packer validate packer.pkr.hcl
          if [ $? -ne 0 ]; then
            echo "Packer template validation failed. Please check the template for errors."
            exit 1
          fi
