name: Database Health Check

on:
  pull_request:
    branches:
      - main

jobs:
  health_check:
    name: Database Health Check
    runs-on: ubuntu-latest

    env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: csye6225

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PostgreSQL and dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y postgresql
            sudo service postgresql start
            sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${{ env.POSTGRES_PASSWORD }}';"
            sudo -u postgres createdb ${{ env.POSTGRES_DB }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest csye6225project/csye6225/tests/test_basic.py
